name: ml_week1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.12
  - pip
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - pip:
      - tensorflow==2.20.0
      - keras==3.13.2
      - google-ml-edu==0.1.3